### ISSUE TITLE
Dependency Injection

### ISSUE THREAD

**Issue by cjprinse** [scrumpy/prosemirror-to-html#17]
Please move the default Marks and Nodes to the constructor.
It's fine to use a default set as arguments, But we want to overwrite even simple Nodes. For example We want to add a class to the heading classes. This is now implossible

**Comment by hanspagel** [comment]
Good idea! Added `->withMarks()` and `->withNodes()`.

**Comment by cjprinse** [comment]
Thank you! :+1:
